import React, { createContext, useContext, useState, ReactNode } from 'react';

export type Language = 'ru' | 'en';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string, params?: Record<string, string>) => string;
}

export const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};

const translations = {
  ru: {
    // BB code
    'bbcode.spoilerReveal': 'Спойлер, нажмите чтобы показать',
    // Navigation
    'nav.profile': 'Профиль',
    'nav.search': 'Поиск',
    'nav.events': 'События',
    'nav.likes': 'Лайки',
    'nav.chats': 'Чаты',
    'nav.talks': 'Форум',
    'nav.friends': 'Друзья',
    'nav.aloevera': 'АлоэВера',
    'nav.settings': 'Настройки',
    'nav.feed': 'Лента',

    // Common
    'common.backToFriends': 'Назад',
    'common.cancel': 'Отмена',
    'common.error': 'Ошибка',
    'common.like': 'Лайк',
    'common.loading': 'Загрузка...',
    'common.match': 'Взаимность!',
    'common.pass': 'Пропустить',
    'common.save': 'Сохранить',
    'common.scrollLeft': 'Прокрутить влево',
    'common.scrollRight': 'Прокрутить вправо',

    // Location
    'location.country': 'Страна',
    'location.region': 'Регион',
    'location.useCustomValue': 'Указать своё значение…',
    'location.regionUnavailable': 'Фильтр по региону недоступен для этой страны',
    'location.clearCountry': 'Очистить страну',
    'location.addSecond': '+ Добавить вторую локацию',
    'location.removeSecond': 'Убрать',
    'location.secondary': 'Дополнительная локация',

    // Profile
    'profile.age': 'Возраст',
    'profile.bio': 'О себе',
    'profile.edit': 'Редактировать профиль',
    'profile.gender': 'Пол',
    'profile.instagram': 'Instagram',
    'profile.instagramPlaceholder': 'username (без @)',
    'profile.location': 'Местоположение',
    'profile.name': 'Имя',
    'profile.notFound': 'Пользователь не найден',
    'profile.photoTooLarge': 'Файл слишком большой. Максимальный размер — 20 МБ',
    'profile.photoUpdated': 'Фото обновлено',
    'profile.photoUploadFailed': 'Не удалось загрузить фото',
    'profile.savePhoto': 'Сохранить фото',
    'profile.savingPhoto': 'Сохранение...',
    'profile.settings': 'Настройки',
    'profile.signOut': 'Выйти',
    'profile.title': 'Ваш профиль',

    // Search
    'search.title': 'Найди тех самых',
    'search.noMoreProfiles': 'Больше профилей пока нет',
    'search.swipeInstructions': 'Свайп вправо - лайк, влево - пропустить, вверх - подробнее',
    'search.moreInfo': 'Подробнее',
    'search.lessInfo': 'Скрыть подробности',
    'search.eventsCount': 'Событий посещено: {count}',
    'search.scrollPrompts': '↕ Прокрутите, чтобы увидеть {count} ответа(ов)',
    'search.filter': 'Фильтр',
    'search.applyFilter': 'Применить',
    'search.clearFilter': 'Сбросить фильтры',
    'search.allCountries': 'Все страны',
    'search.allRegions': 'Все регионы',
    'search.handle': 'Логин (@handle)',
    'search.handlePlaceholder': 'например, alice_99',
    'search.name': 'Имя',
    'search.namePlaceholder': 'например, Анна',
    'search.location': 'Локация',
    'search.ageRange': 'Возраст',
    'search.minAge': 'От',
    'search.maxAge': 'До',
    'search.gender': 'Пол',
    'search.genderAll': 'Любой',
    'search.genderMale': 'Мужчины',
    'search.genderFemale': 'Женщины',
    'search.genderNonBinary': 'Небинарные',
    'search.event': 'Посещённое событие',
    'search.eventAll': 'Все события',
    'search.noAttendedEvents': 'Вы ещё не посещали мероприятий',

    // Chat
    'chat.cancelReply': 'Отменить ответ',
    'chat.photo': 'Фото',
    'chat.replyTo': 'Ответ — {name}',
    'chat.you': 'Ты',
    'chat.edit': 'Редактировать',
    'chat.edited': 'изменено',
    'chat.editingMessage': 'Редактирование сообщения',
    'chat.cancelEdit': 'Отменить редактирование',
    'chat.saveEdit': 'Сохранить',
    'chat.today': 'Сегодня',
    'chat.yesterday': 'Вчера',

    // Events
    'events.applyCode': 'Показать детали по коду',
    'events.attendees': 'участников',
    'events.browseAttendees': 'Смотреть в поиске',
    'events.attendWithInvite': 'Подтвердить участие по коду',
    'events.externalLink': 'Сайт и билеты',
    'events.interested': 'Интересно',
    'events.interestedCount': 'интересуется',
    'events.interestedShort': 'Интересно',
    'events.inviteCodeLabel': 'Код приглашения',
    'events.inviteCodePlaceholder': 'Введите код с приглашения или из ссылки',
    'events.inviteDevHint': 'Локальный mock-бэкенд: код вида MOCK-ATTEND-{id события}',
    'events.join': 'Присоединиться',
    'events.joined': 'Ты участвуешь',
    'events.leaveConfirmAction': 'Покинуть',
    'events.leaveConfirmBody': 'Если ты покинешь событие, вернуться без действующего пригласительного кода не получится.',
    'events.leaveConfirmTitle': 'Покинуть событие?',
    'events.leaveEvent': 'Покинуть событие',
    'events.noPast': 'Нет прошедших событий',
    'events.noUpcoming': 'Нет предстоящих событий',
    'events.notInterested': 'Не интересно',
    'events.past': 'Прошедшие',
    'events.title': 'События АлоэВера',
    'events.upcoming': 'Предстоящие',

    // Friends
    'friends.viewProfile': 'Открыть профиль',

    // Store (merch)
    'store.officialPurchase': 'Купить на официальном сайте',
    'store.officialPurchaseHint': 'Откроется страница товара в официальном магазине',
    'store.noPurchaseLink': 'Ссылка на магазин пока не указана',
    'store.listOfficialLink': 'Официальный магазин',

    // Likes
    'likes.matches': 'Взаимности',
    'likes.sent': 'Отправленные',
    'likes.received': 'Полученные',
    'likes.noMatches': 'Пока нет взаимных лайков',
    'likes.noSent': 'Ты пока никого не лайкнул',
    'likes.noReceived': 'Пока нет лайков',

    // Chats
    'chats.private': 'Личные чаты',
    'chats.group': 'Групповые чаты',
    'chats.noPrivateChats': 'Пока нет личных чатов',
    'chats.noGroupChats': 'Пока нет групповых чатов',
    'chats.startChatting': 'Начни общаться',
    'chats.typeMessage': 'Введи сообщение...',
    'chats.send': 'Отправить',

    // Welcome
    'welcome.title': 'Добро пожаловать в Клуб АлоэВера',
    'welcome.subtitle': 'Для тех, кто на одной волне',
    'welcome.description': 'Ты в правильном месте. Здесь ты найдешь людей, которые разделяют твой вайб и взгляды на жизнь.',
    'welcome.getStarted': 'Начать общение',
    'welcomePhoto.title': 'Добавьте фото профиля',
    'welcomePhoto.description': 'Фото помогает другим узнать вас. Выберите чёткое и приветливое изображение.',
    'welcomePhoto.previewAlt': 'Предпросмотр',
    'welcomePhoto.savePhoto': 'Сохранить фото',
    'welcomePhoto.saving': 'Сохранение…',
    'welcomePhoto.uploadFailed': 'Не удалось загрузить фото',
    'welcomePhoto.photoSaved': 'Фото профиля сохранено!',
    'miniApp.welcome': 'Привет',
    'miniApp.noAccountYet': 'Мы пока не нашли аккаунт, привязанный к вашему профилю Telegram.',
    'miniApp.haveAccount': 'У меня уже есть аккаунт',
    'miniApp.createAccount': 'Создать новый аккаунт',
    
    // Auth
    'auth.accountName': 'Логин',
    'auth.accountNameAvailable': 'Доступен',
    'auth.accountNameChecking': 'Проверка…',
    'auth.accountNameHint': '5–32 буквы, цифры или _, начинается с буквы',
    'auth.accountNameInfo': 'Логин должен быть уникальным и не может быть изменён позже. Он используется, чтобы упоминать вас в обсуждениях, и как прямая ссылка на ваш профиль.',
    'auth.accountNameInvalid': 'Неверный формат',
    'auth.accountNamePlaceholder': 'например, alice_99',
    'auth.accountNameReserved': 'Это зарезервированный логин',
    'auth.accountNameTaken': 'Этот логин уже занят',
    'auth.age': 'Возраст',
    'auth.bio': 'О себе',
    'auth.aboutYourself': 'Расскажите о себе',
    'auth.accountCreated': 'Аккаунт создан! Проверьте почту для подтверждения.',
    'auth.ageMin': 'Должно быть не меньше 18',
    'auth.ageMax': 'Должно быть не больше 99',
    'auth.bioMax': 'О себе — не более 500 символов',
    'auth.countryRequired': 'Укажите страну',
    'auth.countryMax': 'Страна — не более 56 символов',
    'auth.creatingAccount': 'Создание аккаунта…',
    'auth.emailTaken': 'Этот email уже занят',
    'auth.genderRequired': 'Укажите пол',
    'auth.loginFailed': 'Не удалось войти',
    'auth.nameRequired': 'Введите имя',
    'auth.passwordRequired': 'Введите пароль',
    'auth.passwordMin8': 'Минимум 8 символов',
    'auth.passwordUppercase': 'Хотя бы одна заглавная буква',
    'auth.passwordLowercase': 'Хотя бы одна строчная буква',
    'auth.passwordNumber': 'Хотя бы одна цифра',
    'auth.passwordSpecial': 'Хотя бы один специальный символ',
    'auth.passwordValid': 'Пароль соответствует требованиям',
    'auth.regionMax': 'Регион — не более 80 символов',
    'auth.registrationFailed': 'Не удалось зарегистрироваться',
    'auth.secondaryCountryMax': 'Вторая страна — не более 56 символов',
    'auth.secondaryRegionMax': 'Второй регион — не более 80 символов',
    'auth.signingIn': 'Вход…',
    'auth.welcomeBack': 'С возвращением!',
    'common.select': 'Выбрать',
    'auth.cityCountry': 'Город, Страна',
    'auth.createAccount': 'Создать аккаунт',
    'auth.createPassword': 'Создай пароль',
    'auth.email': 'Email',
    'auth.enterEmail': 'Введи свой email',
    'auth.invalidEmail': 'Введите корректный email',
    'auth.enterPassword': 'Введи пароль',
    'auth.female': 'Женский',
    'auth.forgotPassword': 'Забыли пароль?',
    'auth.gender': 'Пол',
    'auth.hasAccount': 'Уже есть аккаунт? Войти',
    'auth.location': 'Местоположение',
    'auth.male': 'Мужской',
    'auth.noAccount': 'Нет аккаунта? Создать',
    'auth.other': 'Другой',
    'auth.password': 'Пароль',
    'auth.signIn': 'Войти',
    'auth.telegram': 'Войти через Telegram',
    'auth.orContinueWith': 'Или войдите через',
    'register.displayName': 'Отображаемое имя',
    'register.displayNamePlaceholder': 'например, Алиса',
    'register.emailIsLogin': 'Email будет использоваться для входа в аккаунт.',
    'register.inviteCode': 'Инвайт-код',
    'register.inviteCodePlaceholder': 'Введите инвайт-код',
    'register.inviteCodeOptional': 'необязательно',
    'register.inviteCodeHint': 'Если у вас есть код приглашения на событие, введите его здесь.',
    'register.inviteCodeInvalid': 'Неверный инвайт-код',
    'register.inviteCodeRequired': 'Введите инвайт-код',
    'invite.banner': 'У вас есть инвайт-код. Войдите или создайте аккаунт, чтобы воспользоваться им.',

    // Forgot password modal
    'forgotPassword.title': 'Восстановление пароля',
    'forgotPassword.emailLabel': 'Email',
    'forgotPassword.submitButton': 'Отправить ссылку',
    'forgotPassword.successMessage': 'Если этот email зарегистрирован, вы получите ссылку для сброса пароля.',
    'forgotPassword.closeButton': 'Закрыть',
    'forgotPassword.errorFallback': 'Не удалось отправить ссылку для сброса пароля',
    // Email verification page
    'verifyEmail.loading': 'Подтверждаем email...',
    'verifyEmail.success': 'Email подтверждён! Теперь вы можете войти.',
    'verifyEmail.successButton': 'Войти',
    'verifyEmail.error': 'Ссылка недействительна или устарела.',
    'verifyEmail.errorButton': 'На главную',
    // Reset password page
    'resetPassword.title': 'Новый пароль',
    'resetPassword.passwordLabel': 'Новый пароль',
    'resetPassword.confirmLabel': 'Подтвердите пароль',
    'resetPassword.submitButton': 'Сохранить пароль',
    'resetPassword.successToast': 'Пароль изменён. Войдите с новым паролем.',
    'resetPassword.errorFallback': 'Не удалось изменить пароль',
    'resetPassword.passwordMismatch': 'Пароли не совпадают',

    // Forum
    'forum.createTopic.titlePrefix': 'Новая тема в',
    'forum.createTopic.titleLabel': 'Заголовок',
    'forum.createTopic.titlePlaceholder': 'Заголовок темы...',
    'forum.createTopic.contentLabel': 'Содержание',
    'forum.createTopic.contentPlaceholder': 'Напишите ваш пост...',
    'forum.createTopic.posting': 'Публикация...',
    'forum.createTopic.post': 'Опубликовать',
    'forum.newTopic': '+ Новая тема',
    'forum.lockedSection': 'Только для активных участников+',
    'forum.replyRestricted': 'Ответы доступны только активным участникам',
    'forum.noviceVisible': 'Видно новичкам',
    'forum.noviceCanReply': 'Новички могут отвечать',
    'forum.editReply': 'Изменить',
    'forum.saveEdit': 'Сохранить',
    'forum.cancelEdit': 'Отмена',
    'forum.savingEdit': 'Сохранение...',
    'forum.editPlaceholder': 'Измените ваш ответ...',
    'forum.editFailed': 'Не удалось сохранить изменения',
    'forum.editedBy': 'изменено {name} · {date}',
    'forum.subscribe': 'Подписаться',
    'forum.unsubscribe': 'Отписаться',
    'forum.subscribed': 'Вы подписаны',
    'forum.subscribeFailed': 'Не удалось изменить подписку',
    'forum.loadOlder': 'Загрузить старые ответы',
    'forum.loadingOlder': 'Загрузка...',

    // Ranks & staff roles
    'rank.novice': 'Новичок',
    'rank.activeMember': 'Активный участник',
    'rank.friendOfAloe': 'Друг AloeVera',
    'rank.aloeCrew': 'Команда AloeVera',
    'staffRole.moderator': 'Мод',
    'staffRole.admin': 'Админ',

    // Common Ground
    'commonGround.title': 'Общее',
    'commonGround.sharedEventsMany': 'Вы оба участвовали в {count} событиях АлоэВера',
    'commonGround.sharedEventOne': 'Вы оба были на {event}',
    'commonGround.sharedUpcomingEvent': 'Оба идут на {event}',
    'commonGround.sharedPromptAnswer': '{prompt}: {answer}',
    'commonGround.sharedRank.aloeCrew': 'Оба — Aloe Crew',
    'commonGround.sharedRank.friendOfAloe': 'Оба — Friend of Aloe',
    'commonGround.sharedCity': 'Оба из {city}',

    // Settings - Photos
    'settings.comingSoon': 'Скоро будет доступно',
    'settings.photos.title': 'Фотографии',
    'settings.photos.add': 'Добавить фото',
    'settings.photos.delete': 'Удалить',
    'settings.photos.dragHint': 'Перетащите, чтобы изменить порядок',
    'settings.photos.save': 'Сохранить',
    'settings.photos.saveSuccess': 'Фото сохранены',
    'settings.photos.saveFailed': 'Не удалось сохранить фото',
    'settings.photos.uploadFailed': 'Не удалось загрузить фото',

    // Settings - Prompts
    'settings.prompts.title': 'Подсказки',
    'settings.prompts.placeholder': 'Выберите вопрос',
    'settings.prompts.pickFromList': 'Выбрать из списка',
    'settings.prompts.answerPlaceholder': 'Ваш ответ',
    'settings.prompts.save': 'Сохранить',
    'settings.prompts.saveSuccess': 'Подсказки сохранены',
    'settings.prompts.saveFailed': 'Не удалось сохранить подсказки',

    // Notifications
    'notifications.bell': 'Уведомления',
    'notifications.markAllRead': 'Отметить все прочитанными',
    'notifications.seeAll': 'Все уведомления',
    'notifications.empty': 'Уведомлений пока нет',
    'notifications.unread': 'Непрочитанные',
    'notifications.all': 'Все',
    'notifications.dismiss': 'Скрыть',
    'notifications.title.likeReceived': '{actor} лайкнул(а) вас',
    'notifications.title.likeReceivedAnonymous': 'Кто-то лайкнул вас',
    'notifications.title.matchCreated': 'Взаимная симпатия с {actor}',
    'notifications.title.messageReceived': '{actor}: {preview}',
    'notifications.title.forumReply': '{actor} ответил(а) в обсуждении',
    'notifications.title.communityBroadcast': '{title}',
    'notifications.title.eventPublished': 'Новое событие: {title}',
    'notifications.title.eventReminder': 'Завтра: {title}',
    'notifications.title.eventInvite': 'Вас пригласили: {title}',
    'notifications.title.rankUp': 'Новый ранг: {rank}!',
    'notifications.settings.title': 'Уведомления',
    'notifications.settings.pauseAll': 'Отключить все уведомления',
    'notifications.settings.snoozeFor': 'Тишина на',
    'notifications.settings.snoozeNever': 'Не активна',
    'notifications.settings.snooze1h': '1 час',
    'notifications.settings.snooze4h': '4 часа',
    'notifications.settings.snooze24h': '24 часа',
    'notifications.settings.dailyHour': 'Ежедневная рассылка (UTC)',
    'notifications.settings.channel.inApp': 'В приложении',
    'notifications.settings.channel.telegram': 'Telegram',
    'notifications.settings.channel.webPush': 'Уведомления браузера',
    'notifications.settings.channel.email': 'Email',
    'notifications.settings.frequency.immediate': 'Сразу',
    'notifications.settings.frequency.hourly': 'Раз в час',
    'notifications.settings.frequency.daily': 'Раз в день',
    'notifications.settings.unavailable.telegram': 'Привяжите Telegram, чтобы включить',
    'notifications.settings.unavailable.webPush': 'Включить на этом устройстве',
    'notifications.settings.unavailable.email': 'Подтвердите email, чтобы включить',
    'notifications.settings.type.likeReceived': 'Новые лайки',
    'notifications.settings.type.matchCreated': 'Новые взаимные симпатии',
    'notifications.settings.type.messageReceived': 'Личные сообщения',
    'notifications.settings.type.forumReplyToThread': 'Ответы в темах, на которые подписан',
    'notifications.settings.type.communityBroadcast': 'Объявления сообщества',
    'notifications.settings.type.eventPublished': 'Новые события',
    'notifications.settings.type.eventReminder': 'Напоминания о событиях',
    'notifications.settings.type.eventInviteReceived': 'Приглашения на события',
    'notifications.settings.type.rankUp': 'Повышение ранга',

    // Feed
    'notifications.feedTitle': 'Лента',
    'feed.viewProfile': 'Открыть профиль',
    'feed.likeBack': 'Лайкнуть в ответ',
    'feed.startChatting': 'Начать общение',
    'feed.openChat': 'Открыть чат',
    'feed.openThread': 'Перейти к теме',
    'feed.viewEvent': 'К событию',
    'feed.repliedIn': 'ответил(а) в',
    'feed.itsAMatch': 'Взаимность!',
    'feed.rankUpFrom': 'Повышение: {previous} → {new}',
    'feed.inviteCode': 'Код приглашения',
  },
  en: {
    // BB code
    'bbcode.spoilerReveal': 'Spoiler, click to reveal',
    // Navigation
    'nav.profile': 'Profile',
    'nav.search': 'Search',
    'nav.events': 'Events',
    'nav.likes': 'Likes',
    'nav.chats': 'Chats',
    'nav.talks': 'Talks',
    'nav.friends': 'Friends',
    'nav.aloevera': 'AloeVera',
    'nav.settings': 'Settings',
    'nav.feed': 'Feed',

    // Common
    'common.backToFriends': 'Back to Friends',
    'common.cancel': 'Cancel',
    'common.error': 'Error',
    'common.like': 'Like',
    'common.loading': 'Loading...',
    'common.match': 'It\'s a Match!',
    'common.pass': 'Pass',
    'common.save': 'Save',
    'common.scrollLeft': 'Scroll left',
    'common.scrollRight': 'Scroll right',

    // Location
    'location.country': 'Country',
    'location.region': 'Region',
    'location.useCustomValue': 'Use custom value…',
    'location.regionUnavailable': 'Region filter not available for this country',
    'location.clearCountry': 'Clear country',
    'location.addSecond': '+ Add second location',
    'location.removeSecond': 'Remove',
    'location.secondary': 'Secondary location',

    // Profile
    'profile.age': 'Age',
    'profile.bio': 'Bio',
    'profile.edit': 'Edit Profile',
    'profile.gender': 'Gender',
    'profile.instagram': 'Instagram',
    'profile.instagramPlaceholder': 'username (without @)',
    'profile.location': 'Location',
    'profile.name': 'Name',
    'profile.notFound': 'User not found',
    'profile.photoTooLarge': 'File too large. Maximum size is 20 MB',
    'profile.photoUpdated': 'Photo updated',
    'profile.photoUploadFailed': 'Failed to upload photo',
    'profile.savePhoto': 'Save photo',
    'profile.savingPhoto': 'Saving...',
    'profile.settings': 'Settings',
    'profile.signOut': 'Sign Out',
    'profile.title': 'Your Profile',

    // Search
    'search.title': 'Find Love',
    'search.noMoreProfiles': 'No more profiles for now',
    'search.swipeInstructions': 'Swipe right to like, left to pass, up for more info',
    'search.moreInfo': 'More info',
    'search.lessInfo': 'Hide details',
    'search.eventsCount': '{count} events attended',
    'search.scrollPrompts': '↕ Scroll for {count} answers',
    'search.filter': 'Filter',
    'search.applyFilter': 'Apply',
    'search.clearFilter': 'Clear filters',
    'search.allCountries': 'All countries',
    'search.allRegions': 'All regions',
    'search.handle': 'Handle (@username)',
    'search.handlePlaceholder': 'e.g. alice_99',
    'search.name': 'Name',
    'search.namePlaceholder': 'e.g. Anna',
    'search.location': 'Location',
    'search.ageRange': 'Age',
    'search.minAge': 'Min',
    'search.maxAge': 'Max',
    'search.gender': 'Gender',
    'search.genderAll': 'Any',
    'search.genderMale': 'Men',
    'search.genderFemale': 'Women',
    'search.genderNonBinary': 'Non-binary',
    'search.event': 'Attended event',
    'search.eventAll': 'All events',
    'search.noAttendedEvents': "You haven't attended any events yet",

    // Chat
    'chat.cancelReply': 'Cancel reply',
    'chat.photo': 'Photo',
    'chat.replyTo': 'Replying to {name}',
    'chat.you': 'You',
    'chat.edit': 'Edit',
    'chat.edited': 'edited',
    'chat.editingMessage': 'Editing message',
    'chat.cancelEdit': 'Cancel editing',
    'chat.saveEdit': 'Save',
    'chat.today': 'Today',
    'chat.yesterday': 'Yesterday',

    // Events
    'events.applyCode': 'Apply code',
    'events.attendees': 'attendees',
    'events.browseAttendees': 'Browse in search',
    'events.attendWithInvite': 'Confirm attendance with code',
    'events.externalLink': 'Website & tickets',
    'events.interested': 'Interested',
    'events.interestedCount': 'interested',
    'events.interestedShort': 'Interest',
    'events.inviteCodeLabel': 'Invite code',
    'events.inviteCodePlaceholder': 'Enter the code from your invite or link',
    'events.inviteDevHint': 'Local mock API: use MOCK-ATTEND-{event id}',
    'events.join': 'Join Event',
    'events.joined': 'Joined',
    'events.leaveConfirmAction': 'Leave',
    'events.leaveConfirmBody': 'If you leave, you won’t be able to rejoin unless you still have an unexpired invite code for this event.',
    'events.leaveConfirmTitle': 'Leave event?',
    'events.leaveEvent': 'Leave event',
    'events.noPast': 'No past events',
    'events.noUpcoming': 'No upcoming events',
    'events.notInterested': 'Not interested',
    'events.past': 'Past',
    'events.title': 'AloeVera Events',
    'events.upcoming': 'Upcoming',

    // Friends
    'friends.viewProfile': 'View profile',

    // Store (merch)
    'store.officialPurchase': 'Buy on official store',
    'store.officialPurchaseHint': 'Opens the product page on the band’s official shop',
    'store.noPurchaseLink': 'Store link not set yet',
    'store.listOfficialLink': 'Official store',

    // Likes
    'likes.matches': 'Matches',
    'likes.sent': 'Sent',
    'likes.received': 'Received',
    'likes.noMatches': 'No matches yet',
    'likes.noSent': 'No likes sent yet',
    'likes.noReceived': 'No likes received yet',

    // Chats
    'chats.private': 'Private Chats',
    'chats.group': 'Group Chats',
    'chats.noPrivateChats': 'No private chats yet',
    'chats.noGroupChats': 'No group chats yet',
    'chats.startChatting': 'Start chatting with your matches',
    'chats.typeMessage': 'Type a message...',
    'chats.send': 'Send',

    // Welcome
    'welcome.title': 'Welcome to AloeVera World',
    'welcome.subtitle': 'Find like-minded people',
    'welcome.description': 'Find like-minded people, fall in love to your favorite melodies, and create harmony in relationships.',
    'welcome.getStarted': 'Start Dating',
    'welcomePhoto.title': 'Add a profile photo',
    'welcomePhoto.description': 'A photo helps others recognize you. Choose something clear and friendly.',
    'welcomePhoto.previewAlt': 'Preview',
    'welcomePhoto.savePhoto': 'Save photo',
    'welcomePhoto.saving': 'Saving...',
    'welcomePhoto.uploadFailed': 'Photo upload failed',
    'welcomePhoto.photoSaved': 'Profile photo saved!',
    'miniApp.welcome': 'Welcome',
    'miniApp.noAccountYet': "We couldn't find an account for your Telegram profile yet.",
    'miniApp.haveAccount': 'I already have an account',
    'miniApp.createAccount': 'Create a new account',
    
    // Auth
    'auth.accountName': 'Account name',
    'auth.accountNameAvailable': 'Available',
    'auth.accountNameChecking': 'Checking…',
    'auth.accountNameHint': '5–32 letters, digits, or underscores. Must start with a letter.',
    'auth.accountNameInfo': 'Your login must be unique and cannot be changed later. It is used to mention you in discussions and as a direct link to your profile.',
    'auth.accountNameInvalid': 'Invalid format',
    'auth.accountNamePlaceholder': 'e.g. alice_99',
    'auth.accountNameReserved': 'This name is reserved',
    'auth.accountNameTaken': 'This name is already taken',
    'auth.age': 'Age',
    'auth.bio': 'Bio',
    'auth.aboutYourself': 'Tell us about yourself',
    'auth.accountCreated': 'Account created! Check your email to verify.',
    'auth.ageMin': 'Must be at least 18',
    'auth.ageMax': 'Must be 99 or under',
    'auth.bioMax': 'Bio must be 500 characters or less',
    'auth.countryRequired': 'Country is required',
    'auth.countryMax': 'Country must be 56 characters or less',
    'auth.creatingAccount': 'Creating account...',
    'auth.emailTaken': 'Email is already taken',
    'auth.genderRequired': 'Gender is required',
    'auth.loginFailed': 'Login failed',
    'auth.nameRequired': 'Name is required',
    'auth.passwordRequired': 'Password is required',
    'auth.passwordMin8': 'At least 8 characters',
    'auth.passwordUppercase': 'One uppercase letter',
    'auth.passwordLowercase': 'One lowercase letter',
    'auth.passwordNumber': 'One number',
    'auth.passwordSpecial': 'One special character',
    'auth.passwordValid': 'Password meets requirements',
    'auth.regionMax': 'Region must be 80 characters or less',
    'auth.registrationFailed': 'Registration failed',
    'auth.secondaryCountryMax': 'Secondary country must be 56 characters or less',
    'auth.secondaryRegionMax': 'Secondary region must be 80 characters or less',
    'auth.signingIn': 'Signing in...',
    'auth.welcomeBack': 'Welcome back!',
    'common.select': 'Select',
    'auth.cityCountry': 'City, Country',
    'auth.createAccount': 'Create Account',
    'auth.createPassword': 'Create a password',
    'auth.email': 'Email',
    'auth.enterEmail': 'Enter your email',
    'auth.invalidEmail': 'Enter a valid email',
    'auth.enterPassword': 'Enter your password',
    'auth.female': 'Female',
    'auth.forgotPassword': 'Forgot password?',
    'auth.gender': 'Gender',
    'auth.hasAccount': 'Already have an account? Sign in',
    'auth.location': 'Location',
    'auth.male': 'Male',
    'auth.noAccount': 'Don\'t have an account? Create one',
    'auth.other': 'Other',
    'auth.password': 'Password',
    'auth.signIn': 'Sign In',
    'auth.telegram': 'Telegram',
    'auth.orContinueWith': 'Or continue with',
    'register.displayName': 'Display Name',
    'register.displayNamePlaceholder': 'e.g. Alice',
    'register.emailIsLogin': 'Your email will be used as your login',
    'register.inviteCode': 'Invite code',
    'register.inviteCodePlaceholder': 'Enter invite code',
    'register.inviteCodeOptional': 'optional',
    'register.inviteCodeHint': 'If you have an event invite code, enter it here.',
    'register.inviteCodeInvalid': 'Invalid invite code',
    'register.inviteCodeRequired': 'Invite code is required',
    'invite.banner': 'You have an invite code. Sign in or create an account to use it.',

    // Forgot password modal
    'forgotPassword.title': 'Reset Password',
    'forgotPassword.emailLabel': 'Email',
    'forgotPassword.submitButton': 'Send Reset Link',
    'forgotPassword.successMessage': "If that email is registered, you'll receive a reset link shortly.",
    'forgotPassword.closeButton': 'Close',
    'forgotPassword.errorFallback': 'Failed to send reset link',
    // Email verification page
    'verifyEmail.loading': 'Verifying your email...',
    'verifyEmail.success': 'Email verified! You can now sign in.',
    'verifyEmail.successButton': 'Sign In',
    'verifyEmail.error': 'This link is invalid or has expired.',
    'verifyEmail.errorButton': 'Go Home',
    // Reset password page
    'resetPassword.title': 'Set New Password',
    'resetPassword.passwordLabel': 'New Password',
    'resetPassword.confirmLabel': 'Confirm Password',
    'resetPassword.submitButton': 'Save Password',
    'resetPassword.successToast': 'Password changed. Sign in with your new password.',
    'resetPassword.errorFallback': 'Failed to reset password',
    'resetPassword.passwordMismatch': 'Passwords do not match',

    // Forum
    'forum.createTopic.titlePrefix': 'New Topic in',
    'forum.createTopic.titleLabel': 'Title',
    'forum.createTopic.titlePlaceholder': 'Topic title...',
    'forum.createTopic.contentLabel': 'Content',
    'forum.createTopic.contentPlaceholder': 'Write your post...',
    'forum.createTopic.posting': 'Posting...',
    'forum.createTopic.post': 'Post Topic',
    'forum.newTopic': '+ New Topic',
    'forum.lockedSection': 'Active Member+ only',
    'forum.replyRestricted': 'Replies for Active Members only',
    'forum.noviceVisible': 'Visible to new users',
    'forum.noviceCanReply': 'New users can reply',
    'forum.editReply': 'Edit',
    'forum.saveEdit': 'Save',
    'forum.cancelEdit': 'Cancel',
    'forum.savingEdit': 'Saving...',
    'forum.editPlaceholder': 'Edit your reply...',
    'forum.editFailed': 'Failed to save changes',
    'forum.editedBy': 'edited by {name} · {date}',
    'forum.subscribe': 'Subscribe',
    'forum.unsubscribe': 'Unsubscribe',
    'forum.subscribed': 'Subscribed',
    'forum.subscribeFailed': 'Could not update subscription',
    'forum.loadOlder': 'Load older replies',
    'forum.loadingOlder': 'Loading...',

    // Ranks & staff roles
    'rank.novice': 'Novice',
    'rank.activeMember': 'Active Member',
    'rank.friendOfAloe': 'Friend of Aloe',
    'rank.aloeCrew': 'Aloe Crew',
    'staffRole.moderator': 'Mod',
    'staffRole.admin': 'Admin',

    // Common Ground
    'commonGround.title': 'In common',
    'commonGround.sharedEventsMany': "You've both been to {count} AloeVera events",
    'commonGround.sharedEventOne': "You've both been to {event}",
    'commonGround.sharedUpcomingEvent': 'Both attending {event}',
    'commonGround.sharedPromptAnswer': '{prompt}: {answer}',
    'commonGround.sharedRank.aloeCrew': 'Both Aloe Crew',
    'commonGround.sharedRank.friendOfAloe': 'Both Friend of Aloe',
    'commonGround.sharedCity': 'Both from {city}',

    // Settings - Photos
    'settings.comingSoon': 'Coming soon',
    'settings.photos.title': 'Photos',
    'settings.photos.add': 'Add photo',
    'settings.photos.delete': 'Delete',
    'settings.photos.dragHint': 'Drag to reorder',
    'settings.photos.save': 'Save',
    'settings.photos.saveSuccess': 'Photos saved',
    'settings.photos.saveFailed': 'Could not save photos',
    'settings.photos.uploadFailed': 'Could not upload photo',

    // Settings - Prompts
    'settings.prompts.title': 'Prompts',
    'settings.prompts.placeholder': 'Pick a prompt',
    'settings.prompts.pickFromList': 'Pick from list',
    'settings.prompts.answerPlaceholder': 'Your answer',
    'settings.prompts.save': 'Save',
    'settings.prompts.saveSuccess': 'Prompts saved',
    'settings.prompts.saveFailed': 'Could not save prompts',

    // Notifications
    'notifications.bell': 'Notifications',
    'notifications.markAllRead': 'Mark all as read',
    'notifications.seeAll': 'See all',
    'notifications.empty': 'No notifications yet',
    'notifications.unread': 'Unread',
    'notifications.all': 'All',
    'notifications.dismiss': 'Dismiss',
    'notifications.title.likeReceived': '{actor} liked you',
    'notifications.title.likeReceivedAnonymous': 'Someone liked you',
    'notifications.title.matchCreated': 'New match with {actor}',
    'notifications.title.messageReceived': '{actor}: {preview}',
    'notifications.title.forumReply': '{actor} replied in a thread',
    'notifications.title.communityBroadcast': '{title}',
    'notifications.title.eventPublished': 'New event: {title}',
    'notifications.title.eventReminder': 'Event tomorrow: {title}',
    'notifications.title.eventInvite': "You're invited: {title}",
    'notifications.title.rankUp': "You're now {rank}!",
    'notifications.settings.title': 'Notifications',
    'notifications.settings.pauseAll': 'Pause all notifications',
    'notifications.settings.snoozeFor': 'Snooze for',
    'notifications.settings.snoozeNever': 'Never',
    'notifications.settings.snooze1h': '1 hour',
    'notifications.settings.snooze4h': '4 hours',
    'notifications.settings.snooze24h': '24 hours',
    'notifications.settings.dailyHour': 'Daily digest hour (UTC)',
    'notifications.settings.channel.inApp': 'In-app',
    'notifications.settings.channel.telegram': 'Telegram',
    'notifications.settings.channel.webPush': 'Browser push',
    'notifications.settings.channel.email': 'Email',
    'notifications.settings.frequency.immediate': 'Immediate',
    'notifications.settings.frequency.hourly': 'Hourly digest',
    'notifications.settings.frequency.daily': 'Daily digest',
    'notifications.settings.unavailable.telegram': 'Link your Telegram account to enable',
    'notifications.settings.unavailable.webPush': 'Enable on this device',
    'notifications.settings.unavailable.email': 'Verify your email to enable',
    'notifications.settings.type.likeReceived': 'New likes',
    'notifications.settings.type.matchCreated': 'New matches',
    'notifications.settings.type.messageReceived': 'Private messages',
    'notifications.settings.type.forumReplyToThread': 'Replies in topics you follow',
    'notifications.settings.type.communityBroadcast': 'Community announcements',
    'notifications.settings.type.eventPublished': 'New events',
    'notifications.settings.type.eventReminder': 'Event reminders',
    'notifications.settings.type.eventInviteReceived': 'Event invitations',
    'notifications.settings.type.rankUp': 'Rank promotions',

    // Feed
    'notifications.feedTitle': 'Feed',
    'feed.viewProfile': 'View profile',
    'feed.likeBack': 'Like back',
    'feed.startChatting': 'Start chatting',
    'feed.openChat': 'Open chat',
    'feed.openThread': 'Open thread',
    'feed.viewEvent': 'View event',
    'feed.repliedIn': 'replied in',
    'feed.itsAMatch': "It's a match!",
    'feed.rankUpFrom': 'Promoted: {previous} → {new}',
    'feed.inviteCode': 'Invite code',
  },
};

interface LanguageProviderProps {
  children: ReactNode;
}

export const LanguageProvider: React.FC<LanguageProviderProps> = ({ children }) => {
  const [language, setLanguage] = useState<Language>('ru');

  const t = (key: string, params?: Record<string, string>): string => {
    let str = translations[language][key as keyof typeof translations['ru']] || key;
    if (params) {
      for (const [k, v] of Object.entries(params)) {
        str = str.replace(`{${k}}`, v);
      }
    }
    return str;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};
